name: flutter_diploma_3d_viewer_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  model_viewer: ^0.8.1
  bottom_navy_bar: ^6.0.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Astronaut.glb
    - lib/assets/bag.glb
    - lib/assets/uploads-files-2382092-untitled.glb
    - lib/assets/uploads-files-3641433-Octopus_toy.glb
    - lib/assets/uploads-files-3803418-bed83h.glb
    - lib/assets/uploads-files-4018512-ice+cream++only.glb